"""
Test for verifying ray_data_bytes_task_outputs_generated Prometheus metric.

This test validates that the "Bytes Generated by Tasks / Second" metric
(ray_data_bytes_task_outputs_generated) is correctly exported to Prometheus.

Usage:
    pytest python/ray/data/tests/test_bytes_task_outputs_generated_metric.py -v -s
"""

import time

import pytest
import requests

import ray
from ray._common.test_utils import wait_for_condition
from ray.data.tests.conftest import restore_data_context  # noqa: F401


def fetch_metrics_from_prometheus(metrics_export_port: int) -> str:
    """Fetch raw metrics from Prometheus endpoint."""
    try:
        response = requests.get(f"http://127.0.0.1:{metrics_export_port}/metrics")
        response.raise_for_status()
        return response.text
    except requests.exceptions.ConnectionError:
        return ""


def get_metric_value(metrics_text: str, metric_name: str) -> float:
    """Extract metric value from Prometheus text format."""
    for line in metrics_text.split("\n"):
        if line.startswith(metric_name) and not line.startswith("#"):
            # Parse lines like: metric_name{labels} value
            parts = line.split()
            if len(parts) >= 2:
                try:
                    return float(parts[-1])
                except ValueError:
                    continue
    return 0.0


def get_all_metric_values(metrics_text: str, metric_name: str) -> list:
    """Extract all metric values for a given metric name (across all labels)."""
    values = []
    for line in metrics_text.split("\n"):
        if line.startswith(metric_name) and not line.startswith("#"):
            parts = line.split()
            if len(parts) >= 2:
                try:
                    values.append(float(parts[-1]))
                except ValueError:
                    continue
    return values


@pytest.fixture
def ray_start_with_metrics():
    """Start Ray with metrics collection enabled."""
    # Shutdown any existing Ray instance first
    if ray.is_initialized():
        ray.shutdown()
    ray.init(
        num_cpus=4,
        include_dashboard=False,
        _system_config={
            "metrics_report_interval_ms": 500,
        },
    )
    yield
    ray.shutdown()


class TestBytesTaskOutputsGeneratedMetric:
    """Tests for bytes_task_outputs_generated metric."""

    def test_bytes_task_outputs_generated_via_stats(
        self, restore_data_context, ray_start_with_metrics  # noqa: F811
    ):
        """Test that bytes_task_outputs_generated is tracked correctly in stats."""
        # Create a dataset with map operation that generates output blocks
        # Use simple map instead of map_batches for clearer behavior
        ds = ray.data.range(100, override_num_blocks=4).map(
            lambda row: {"id": row["id"], "value": row["id"] * 2}
        )

        # Consume the dataset
        result = ds.take_all()
        assert len(result) == 100, f"Expected 100 rows, got {len(result)}"

        # Check stats
        stats = ds._get_stats_summary()
        extra_metrics = stats.extra_metrics

        # Verify bytes_task_outputs_generated is present and > 0
        assert "bytes_task_outputs_generated" in extra_metrics, (
            f"bytes_task_outputs_generated not found in extra_metrics. "
            f"Available keys: {list(extra_metrics.keys())}"
        )
        bytes_generated = extra_metrics["bytes_task_outputs_generated"]
        assert bytes_generated > 0, (
            f"Expected bytes_task_outputs_generated > 0, got {bytes_generated}"
        )

        # Also verify related metrics
        assert "num_task_outputs_generated" in extra_metrics
        assert extra_metrics["num_task_outputs_generated"] > 0

        assert "rows_task_outputs_generated" in extra_metrics
        assert extra_metrics["rows_task_outputs_generated"] == 100

    def test_bytes_task_outputs_generated_with_transform(
        self, restore_data_context, ray_start_with_metrics  # noqa: F811
    ):
        """Test bytes_task_outputs_generated with a transform that changes data size."""
        # Create data and apply a transform that increases size
        ds = ray.data.range(50, override_num_blocks=2).map(
            lambda row: {"id": row["id"], "data": "x" * 1000}  # Add 1KB string per row
        )

        result = ds.take_all()
        assert len(result) == 50

        stats = ds._get_stats_summary()
        bytes_generated = stats.extra_metrics.get("bytes_task_outputs_generated", 0)

        # With 50 rows * ~1KB each, we expect significant bytes generated
        # The actual size will include Arrow overhead, so just verify it's substantial
        assert bytes_generated > 10000, (
            f"Expected bytes_task_outputs_generated > 10000 (50 rows * ~1KB), "
            f"got {bytes_generated}"
        )

    def test_bytes_task_outputs_generated_zero_for_input_only(
        self, restore_data_context, ray_start_with_metrics  # noqa: F811
    ):
        """Test that InputDataBuffer has 0 bytes_task_outputs_generated."""
        # Create a simple range dataset without any map operations
        ds = ray.data.range(10, override_num_blocks=2)

        # Just read the data without any transforms
        result = ds.take_all()
        assert len(result) == 10

        # For pure input (no map), bytes_task_outputs_generated should be 0
        # because InputDataBuffer doesn't generate output blocks via tasks
        stats = ds._get_stats_summary()

        # The final stats are from the last operator in the pipeline
        # For a pure range() without transforms, this will be the ReadRange operator
        bytes_generated = stats.extra_metrics.get("bytes_task_outputs_generated", 0)

        # ReadRange operator DOES generate task outputs, so this should be > 0
        assert bytes_generated > 0, (
            f"ReadRange should have bytes_task_outputs_generated > 0, "
            f"got {bytes_generated}"
        )


class TestPrometheusMetricExport:
    """Tests for Prometheus metric export."""

    @pytest.mark.skipif(
        not pytest.importorskip("requests", reason="requests not installed"),
        reason="requests not installed",
    )
    def test_prometheus_metric_export(
        self, restore_data_context  # noqa: F811
    ):
        """Test that bytes_task_outputs_generated is exported to Prometheus."""
        if ray.is_initialized():
            ray.shutdown()
        ray.init(
            num_cpus=4,
            _system_config={
                "metrics_report_interval_ms": 500,
            },
        )

        try:
            # Get metrics export port
            node_info = ray.nodes()[0]
            metrics_export_port = node_info["MetricsExportPort"]

            # Create and execute a dataset with map operations
            ds = ray.data.range(100, override_num_blocks=4).map(
                lambda row: {"id": row["id"], "value": row["id"] * 2}
            )
            result = ds.take_all()
            assert len(result) == 100, f"Expected 100 rows, got {len(result)}"

            # Wait for metrics to be exported
            def check_metric_exists():
                metrics_text = fetch_metrics_from_prometheus(metrics_export_port)
                if not metrics_text:
                    return False

                # Check for the metric (with ray_ prefix)
                # The metric name in Prometheus is ray_data_bytes_task_outputs_generated
                if "ray_data_bytes_task_outputs_generated" in metrics_text:
                    values = get_all_metric_values(
                        metrics_text, "ray_data_bytes_task_outputs_generated"
                    )
                    # Check if any value is > 0
                    return any(v > 0 for v in values)
                return False

            wait_for_condition(
                check_metric_exists,
                timeout=30,
                retry_interval_ms=1000,
            )

            # Final verification
            metrics_text = fetch_metrics_from_prometheus(metrics_export_port)
            assert "ray_data_bytes_task_outputs_generated" in metrics_text, (
                "ray_data_bytes_task_outputs_generated not found in Prometheus metrics"
            )

            values = get_all_metric_values(
                metrics_text, "ray_data_bytes_task_outputs_generated"
            )
            assert any(v > 0 for v in values), (
                f"Expected at least one ray_data_bytes_task_outputs_generated > 0, "
                f"got values: {values}"
            )

        finally:
            ray.shutdown()

    @pytest.mark.skipif(
        not pytest.importorskip("requests", reason="requests not installed"),
        reason="requests not installed",
    )
    def test_prometheus_related_metrics(
        self, restore_data_context  # noqa: F811
    ):
        """Test that related output metrics are also exported."""
        if ray.is_initialized():
            ray.shutdown()
        ray.init(
            num_cpus=4,
            _system_config={
                "metrics_report_interval_ms": 500,
            },
        )

        try:
            node_info = ray.nodes()[0]
            metrics_export_port = node_info["MetricsExportPort"]

            # Create and execute a dataset
            ds = ray.data.range(100, override_num_blocks=4).map(
                lambda row: {"id": row["id"], "value": row["id"] * 2}
            )
            result = ds.take_all()
            assert len(result) == 100, f"Expected 100 rows, got {len(result)}"

            # Wait for metrics
            time.sleep(2)

            metrics_text = fetch_metrics_from_prometheus(metrics_export_port)

            # List of related metrics that should be present
            expected_metrics = [
                "ray_data_bytes_task_outputs_generated",
                "ray_data_num_task_outputs_generated",
                "ray_data_rows_task_outputs_generated",
                "ray_data_output_bytes",  # This is the gauge that uses bytes_task_outputs_generated
            ]

            missing_metrics = []
            for metric_name in expected_metrics:
                if metric_name not in metrics_text:
                    missing_metrics.append(metric_name)

            assert not missing_metrics, (
                f"Missing expected metrics: {missing_metrics}\n"
                f"Available metrics containing 'data': "
                f"{[line for line in metrics_text.split(chr(10)) if 'ray_data' in line and not line.startswith('#')][:20]}"
            )

        finally:
            ray.shutdown()


class TestMetricWithDifferentOperators:
    """Test metrics with different operator types."""

    def test_map_operator_generates_bytes(
        self, restore_data_context  # noqa: F811
    ):
        ray.init(address="auto")
        """Test that map operator generates bytes_task_outputs_generated."""
        ds = ray.data.range(50, override_num_blocks=2).map(
            lambda row: {"id": row["id"] * 2}
        )
        ds.take_all()

        stats = ds._get_stats_summary()
        assert stats.extra_metrics.get("bytes_task_outputs_generated", 0) > 0

    def test_filter_operator_generates_bytes(
        self, restore_data_context, ray_start_with_metrics  # noqa: F811
    ):
        """Test that filter operator generates bytes_task_outputs_generated."""
        ds = ray.data.range(50, override_num_blocks=2).filter(lambda row: row["id"] > 25)
        result = ds.take_all()

        # Filter should return rows where id > 25 (26-49 = 24 rows)
        assert len(result) == 24

        stats = ds._get_stats_summary()
        assert stats.extra_metrics.get("bytes_task_outputs_generated", 0) > 0

    def test_flat_map_operator_generates_bytes(
        self, restore_data_context, ray_start_with_metrics  # noqa: F811
    ):
        """Test that flat_map operator generates bytes_task_outputs_generated."""
        ds = ray.data.range(10, override_num_blocks=2).flat_map(
            lambda row: [{"id": row["id"]}, {"id": row["id"] + 100}]
        )
        result = ds.take_all()

        # flat_map doubles the rows
        assert len(result) == 20

        stats = ds._get_stats_summary()
        assert stats.extra_metrics.get("bytes_task_outputs_generated", 0) > 0


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-v", "-s"]))
